# Generated by Django on manually

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_master_admin(apps, schema_editor):
    import os
    User = apps.get_model('users', 'User')
    admin_user = os.getenv('MASTER_ADMIN_USER', 'aum')
    admin_email = os.getenv('MASTER_ADMIN_EMAIL', 'aumpatro22@gmail.com')
    admin_pass = os.getenv('MASTER_ADMIN_PASS', 'secure-default-pass-change-me')

    if not User.objects.filter(username=admin_user).exists():
        User.objects.create(
            username=admin_user,
            email=admin_email,
            password=make_password(admin_pass),
            role='ADMIN',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )

def revert_master_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='aum').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactmessage_platformstatus_report_status_and_more'),
    ]

    operations = [
        migrations.RunPython(create_master_admin, revert_master_admin),
    ]
