# Generated by Django 4.2.7 on 2026-06-20 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0004_remove_directmessage_is_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="privacy_setting",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("CONNECTIONS_ONLY", "Connections Only"),
                    ("PRIVATE", "Private"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProfileTimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="CircleConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("FRIEND", "Friend"),
                            ("FAMILY", "Family"),
                            ("SUPPORTER", "Supporter"),
                        ],
                        default="FRIEND",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("sender", "receiver")},
            },
        ),
    ]
