# Generated by Django 4.2.7 on 2026-06-20 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("is_invite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="communitymessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="community",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="community",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="communitymessage",
            name="channel",
        ),
        migrations.AddField(
            model_name="community",
            name="community_type",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="communities/covers/"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="icon_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="communities/icons/"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="community",
            name="rules",
            field=models.TextField(
                default="1. Be respectful.\n2. No harassment.\n3. Support others kindly.\n4. No spam."
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="welcome_message",
            field=models.TextField(
                default="We're sorry you're here, but you're not alone."
            ),
        ),
        migrations.AddField(
            model_name="communitymessage",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communitymessage",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_community_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communitymessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community_messages/"
            ),
        ),
        migrations.AddField(
            model_name="communitymessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CO_ADMIN", "Co-Admin"),
                    ("MEMBER", "Member"),
                ],
                default="MEMBER",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Channel",
        ),
        migrations.AddField(
            model_name="communityjoinrequest",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="communityjoinrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_join_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communityjoinrequest",
            unique_together={("user", "community", "is_invite")},
        ),
    ]
