# Generated by Django 4.2.7 on 2026-06-21 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("memorials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_memories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="memorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="memorials.memorial",
            ),
        ),
        migrations.AddField(
            model_name="memorialphoto",
            name="memorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="memorials.memorial",
            ),
        ),
        migrations.AddField(
            model_name="memorial",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memorials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memorial",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="memorials", to="memorials.experiencetag"
            ),
        ),
        migrations.AddField(
            model_name="contributorinvitation",
            name="invited_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contributorinvitation",
            name="memorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="memorials.memorial",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="memorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="memorials.memorial",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candle",
            name="memorial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candles",
                to="memorials.memorial",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributorinvitation",
            unique_together={("memorial", "invited_user")},
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("memorial", "user")},
        ),
    ]
