# Generated by Django 4.2.7 on 2026-06-18 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("memorials", "0002_memorial_public_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memorial",
            old_name="date_of_birth",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="memorial",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="memorial",
            old_name="date_of_passing",
            new_name="passing_date",
        ),
        migrations.RenameField(
            model_name="memorial",
            old_name="creator",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="memorial",
            old_name="image",
            new_name="profile_image",
        ),
        migrations.AlterField(
            model_name="memorial",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memorials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="memorial",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="memorial_profiles/"
            ),
        ),
        migrations.AddField(
            model_name="memorial",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="memorial_covers/"
            ),
        ),
        migrations.AddField(
            model_name="memorial",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private"),
                    ("FAMILY_ONLY", "Family Only"),
                    ("PUBLIC", "Public"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="timeline_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "memorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="memorials.memorial",
                    ),
                ),
            ],
            options={
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="MemorialPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="memorial_photos/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "memorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="memorials.memorial",
                    ),
                ),
            ],
        ),
    ]
