# Generated by Django 4.2.7 on 2026-06-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("memorials", "0003_rename_date_of_birth_memorial_birth_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("story", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="memories/"),
                ),
                (
                    "voice_note",
                    models.FileField(blank=True, null=True, upload_to="memory_voices/"),
                ),
                ("memory_date", models.DateField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("FAMILY_ONLY", "Family Only"),
                            ("PUBLIC", "Public"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "memorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="memorials.memorial",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
