# Generated by Django 4.2.7 on 2026-06-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tales", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tale",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tale",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
