from django.urls import path
from . import api_views
from . import admin_api_views

urlpatterns = [
    path('auth/register/', api_views.register_view, name='api_register'),
    path('auth/login/', api_views.login_view, name='api_login'),
    path('auth/logout/', api_views.logout_view, name='api_logout'),
    path('auth/me/', api_views.me_view, name='api_me'),
    path('users/search/', api_views.search_profiles, name='api_search_profiles'),
    path('users/<str:username>/', api_views.profile_detail, name='api_profile_detail'),
    path('conversations/', api_views.list_conversations, name='api_conversations_list'),
    path('conversations/create/', api_views.get_or_create_conversation, name='api_conversations_create'),
    path('conversations/<int:pk>/messages/', api_views.conversation_messages, name='api_conversations_messages'),
    path('conversations/<int:pk>/messages/send/', api_views.send_direct_message, name='api_conversations_messages_send'),
    path('conversations/<int:pk>/block/', api_views.toggle_block_conversation, name='api_conversations_block'),
    path('users/profile/update/', api_views.profile_update, name='api_profile_update'),
    path('profiles/timeline/', api_views.add_profile_timeline_event, name='api_add_profile_timeline_event'),
    path('profiles/timeline/<int:pk>/delete/', api_views.delete_profile_timeline_event, name='api_delete_profile_timeline_event'),
    path('connections/', api_views.list_connections, name='api_list_connections'),
    path('connections/request/', api_views.request_connection, name='api_request_connection'),
    path('connections/<int:pk>/respond/', api_views.respond_connection, name='api_respond_connection'),
    path('connections/block/', api_views.block_user_directly, name='api_block_user_directly'),
    path('reports/', api_views.file_report, name='api_file_report'),
    path('react/', api_views.react_toggle, name='api_react'),

    # Public contact submit
    path('contact/', admin_api_views.public_submit_contact, name='api_public_submit_contact'),

    # Admin Panel APIs
    path('admin/dashboard/', admin_api_views.admin_dashboard, name='api_admin_dashboard'),
    path('admin/global-search/', admin_api_views.admin_global_search, name='api_admin_global_search'),
    path('admin/users/', admin_api_views.admin_users_list, name='api_admin_users_list'),
    path('admin/users/<int:pk>/status/', admin_api_views.admin_user_status_action, name='api_admin_user_status_action'),
    path('admin/users/<int:pk>/notes/', admin_api_views.admin_user_notes, name='api_admin_user_notes'),
    path('admin/users/<int:pk>/profile/', admin_api_views.admin_user_profile_detail, name='api_admin_user_profile_detail'),
    path('admin/sessions/', admin_api_views.admin_sessions_list, name='api_admin_sessions_list'),
    path('admin/memorials/', admin_api_views.admin_memorials_list, name='api_admin_memorials_list'),
    path('admin/memorials/<int:pk>/action/', admin_api_views.admin_memorial_action, name='api_admin_memorial_action'),
    path('admin/tales/', admin_api_views.admin_tales_list, name='api_admin_tales_list'),
    path('admin/tales/<int:pk>/action/', admin_api_views.admin_tale_action, name='api_admin_tale_action'),
    path('admin/communities/', admin_api_views.admin_communities_list, name='api_admin_communities_list'),
    path('admin/communities/<int:pk>/action/', admin_api_views.admin_community_action, name='api_admin_community_action'),
    path('admin/communities/<int:pk>/details/', admin_api_views.admin_community_details, name='api_admin_community_details'),
    path('admin/messages/', admin_api_views.admin_messages_list, name='api_admin_messages_list'),
    path('admin/messages/<int:pk>/action/', admin_api_views.admin_message_action, name='api_admin_message_action'),
    path('admin/reports/', admin_api_views.admin_reports_list, name='api_admin_reports_list'),
    path('admin/reports/<int:pk>/action/', admin_api_views.admin_report_action, name='api_admin_report_action'),
    path('admin/media/', admin_api_views.admin_media_list, name='api_admin_media_list'),
    path('admin/ownership-requests/', admin_api_views.admin_ownership_requests_list, name='api_admin_ownership_requests_list'),
    path('admin/ownership-requests/<int:pk>/action/', admin_api_views.admin_ownership_request_action, name='api_admin_ownership_request_action'),
    path('admin/platform-status/', admin_api_views.admin_platform_status, name='api_admin_platform_status'),
    path('admin/database-health/', admin_api_views.admin_database_health, name='api_admin_database_health'),
    path('admin/audit-logs/', admin_api_views.admin_audit_logs_list, name='api_admin_audit_logs_list'),
    path('admin/recovery/', admin_api_views.admin_recovery_list, name='api_admin_recovery_list'),
    path('admin/recovery/restore/', admin_api_views.admin_recovery_restore, name='api_admin_recovery_restore'),
    path('admin/contact-messages/', admin_api_views.admin_contact_messages, name='api_admin_contact_messages'),
]
